<?php

/**
 * BaseHotideas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $extract
 * @property string $price
 * @property clob $body
 * @property integer $image
 * @property integer $categoryidea
 * @property integer $author
 * @property boolean $is_active
 * @property Categoryidea $Categoryidea
 * @property DmMedia $Image
 * @property DmUser $Author
 * 
 * @method string       getTitle()        Returns the current record's "title" value
 * @method string       getExtract()      Returns the current record's "extract" value
 * @method string       getPrice()        Returns the current record's "price" value
 * @method clob         getBody()         Returns the current record's "body" value
 * @method integer      getImage()        Returns the current record's "image" value
 * @method integer      getCategoryidea() Returns the current record's "categoryidea" value
 * @method integer      getAuthor()       Returns the current record's "author" value
 * @method boolean      getIsActive()     Returns the current record's "is_active" value
 * @method Categoryidea getCategoryidea() Returns the current record's "Categoryidea" value
 * @method DmMedia      getImage()        Returns the current record's "Image" value
 * @method DmUser       getAuthor()       Returns the current record's "Author" value
 * @method Hotideas     setTitle()        Sets the current record's "title" value
 * @method Hotideas     setExtract()      Sets the current record's "extract" value
 * @method Hotideas     setPrice()        Sets the current record's "price" value
 * @method Hotideas     setBody()         Sets the current record's "body" value
 * @method Hotideas     setImage()        Sets the current record's "image" value
 * @method Hotideas     setCategoryidea() Sets the current record's "categoryidea" value
 * @method Hotideas     setAuthor()       Sets the current record's "author" value
 * @method Hotideas     setIsActive()     Sets the current record's "is_active" value
 * @method Hotideas     setCategoryidea() Sets the current record's "Categoryidea" value
 * @method Hotideas     setImage()        Sets the current record's "Image" value
 * @method Hotideas     setAuthor()       Sets the current record's "Author" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotideas extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hotideas');
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('extract', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('price', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('image', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('categoryidea', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categoryidea', array(
             'local' => 'categoryidea',
             'foreign' => 'id'));

        $this->hasOne('DmMedia as Image', array(
             'local' => 'image',
             'foreign' => 'id'));

        $this->hasOne('DmUser as Author', array(
             'local' => 'author',
             'foreign' => 'id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'extract',
              2 => 'body',
              3 => 'is_active',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $dmversionable1 = new Doctrine_Template_DmVersionable();
        $i18n0->addChild($dmversionable1);
        $this->actAs($dmsortable0);
        $this->actAs($i18n0);
    }
}