<?php

/**
 * BaseExperience
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property date $datedeb
 * @property date $datefin
 * @property integer $cv
 * @property Cv $Cv
 * 
 * @method string     getTitle()       Returns the current record's "title" value
 * @method clob       getDescription() Returns the current record's "description" value
 * @method date       getDatedeb()     Returns the current record's "datedeb" value
 * @method date       getDatefin()     Returns the current record's "datefin" value
 * @method integer    getCv()          Returns the current record's "cv" value
 * @method Cv         getCv()          Returns the current record's "Cv" value
 * @method Experience setTitle()       Sets the current record's "title" value
 * @method Experience setDescription() Sets the current record's "description" value
 * @method Experience setDatedeb()     Sets the current record's "datedeb" value
 * @method Experience setDatefin()     Sets the current record's "datefin" value
 * @method Experience setCv()          Sets the current record's "cv" value
 * @method Experience setCv()          Sets the current record's "Cv" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExperience extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('experience');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('datedeb', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('datefin', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('cv', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cv', array(
             'local' => 'cv',
             'foreign' => 'id'));
    }
}