<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Jobcategory', 'doctrine');

/**
 * BaseJobcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idjobcategory
 * @property string $titlejobcategory
 * @property Doctrine_Collection $Subjobcategory
 * 
 * @method integer             getIdjobcategory()    Returns the current record's "idjobcategory" value
 * @method string              getTitlejobcategory() Returns the current record's "titlejobcategory" value
 * @method Doctrine_Collection getSubjobcategory()   Returns the current record's "Subjobcategory" collection
 * @method Jobcategory         setIdjobcategory()    Sets the current record's "idjobcategory" value
 * @method Jobcategory         setTitlejobcategory() Sets the current record's "titlejobcategory" value
 * @method Jobcategory         setSubjobcategory()   Sets the current record's "Subjobcategory" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobcategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobcategory');
        $this->hasColumn('idjobcategory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('titlejobcategory', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subjobcategory', array(
             'local' => 'idjobcategory',
             'foreign' => 'idjobcategory'));
    }
}