<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sector', 'doctrine');

/**
 * BaseSector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_sector
 * @property string $sectorname
 * @property integer $totalsuppliersector
 * @property Doctrine_Collection $Workinsector
 * 
 * @method integer             getIdSector()            Returns the current record's "id_sector" value
 * @method string              getSectorname()          Returns the current record's "sectorname" value
 * @method integer             getTotalsuppliersector() Returns the current record's "totalsuppliersector" value
 * @method Doctrine_Collection getWorkinsector()        Returns the current record's "Workinsector" collection
 * @method Sector              setIdSector()            Sets the current record's "id_sector" value
 * @method Sector              setSectorname()          Sets the current record's "sectorname" value
 * @method Sector              setTotalsuppliersector() Sets the current record's "totalsuppliersector" value
 * @method Sector              setWorkinsector()        Sets the current record's "Workinsector" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sector');
        $this->hasColumn('id_sector', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sectorname', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('totalsuppliersector', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Workinsector', array(
             'local' => 'id_sector',
             'foreign' => 'id_sector'));
    }
}