<?php

/**
 * BaseSubjobcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $jobcategory
 * @property Jobcategory $Jobcategory
 * @property Doctrine_Collection $Job
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method integer             getJobcategory() Returns the current record's "jobcategory" value
 * @method Jobcategory         getJobcategory() Returns the current record's "Jobcategory" value
 * @method Doctrine_Collection getJob()         Returns the current record's "Job" collection
 * @method Subjobcategory      setTitle()       Sets the current record's "title" value
 * @method Subjobcategory      setJobcategory() Sets the current record's "jobcategory" value
 * @method Subjobcategory      setJobcategory() Sets the current record's "Jobcategory" value
 * @method Subjobcategory      setJob()         Sets the current record's "Job" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubjobcategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subjobcategory');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('jobcategory', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jobcategory', array(
             'local' => 'jobcategory',
             'foreign' => 'id'));

        $this->hasMany('Job', array(
             'local' => 'id',
             'foreign' => 'subjobcategory'));
    }
}