<?php

/**
 * BaseForumtopicview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $author
 * @property integer $topic
 * @property date $created_at
 * 
 * @method integer        getAuthor()     Returns the current record's "author" value
 * @method integer        getTopic()      Returns the current record's "topic" value
 * @method date           getCreatedAt()  Returns the current record's "created_at" value
 * @method Forumtopicview setAuthor()     Sets the current record's "author" value
 * @method Forumtopicview setTopic()      Sets the current record's "topic" value
 * @method Forumtopicview setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumtopicview extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forumtopicview');
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('topic', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}