<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Avendu', 'doctrine');

/**
 * BaseAvendu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iduser
 * @property integer $idideas
 * @property date $datevente
 * @property integer $envoieconfirmation
 * @property float $prixvente
 * @property Ideas $Ideas
 * @property User $User
 * 
 * @method integer getIduser()             Returns the current record's "iduser" value
 * @method integer getIdideas()            Returns the current record's "idideas" value
 * @method date    getDatevente()          Returns the current record's "datevente" value
 * @method integer getEnvoieconfirmation() Returns the current record's "envoieconfirmation" value
 * @method float   getPrixvente()          Returns the current record's "prixvente" value
 * @method Ideas   getIdeas()              Returns the current record's "Ideas" value
 * @method User    getUser()               Returns the current record's "User" value
 * @method Avendu  setIduser()             Sets the current record's "iduser" value
 * @method Avendu  setIdideas()            Sets the current record's "idideas" value
 * @method Avendu  setDatevente()          Sets the current record's "datevente" value
 * @method Avendu  setEnvoieconfirmation() Sets the current record's "envoieconfirmation" value
 * @method Avendu  setPrixvente()          Sets the current record's "prixvente" value
 * @method Avendu  setIdeas()              Sets the current record's "Ideas" value
 * @method Avendu  setUser()               Sets the current record's "User" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvendu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avendu');
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idideas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('datevente', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('envoieconfirmation', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('prixvente', 'float', 15, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ideas', array(
             'local' => 'idideas',
             'foreign' => 'idideas'));

        $this->hasOne('User', array(
             'local' => 'iduser',
             'foreign' => 'iduser'));
    }
}