<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Documenttype', 'doctrine');

/**
 * BaseDocumenttype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddocumenttype
 * @property string $documenttypename
 * @property Doctrine_Collection $Formatlistaccept
 * 
 * @method integer             getIddocumenttype()   Returns the current record's "iddocumenttype" value
 * @method string              getDocumenttypename() Returns the current record's "documenttypename" value
 * @method Doctrine_Collection getFormatlistaccept() Returns the current record's "Formatlistaccept" collection
 * @method Documenttype        setIddocumenttype()   Sets the current record's "iddocumenttype" value
 * @method Documenttype        setDocumenttypename() Sets the current record's "documenttypename" value
 * @method Documenttype        setFormatlistaccept() Sets the current record's "Formatlistaccept" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumenttype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documenttype');
        $this->hasColumn('iddocumenttype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('documenttypename', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Formatlistaccept', array(
             'local' => 'iddocumenttype',
             'foreign' => 'iddocumenttype'));
    }
}