<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Country', 'doctrine');

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcountry
 * @property string $namecountry
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $Job
 * 
 * @method integer             getIdcountry()   Returns the current record's "idcountry" value
 * @method string              getNamecountry() Returns the current record's "namecountry" value
 * @method Doctrine_Collection getCity()        Returns the current record's "City" collection
 * @method Doctrine_Collection getJob()         Returns the current record's "Job" collection
 * @method Country             setIdcountry()   Sets the current record's "idcountry" value
 * @method Country             setNamecountry() Sets the current record's "namecountry" value
 * @method Country             setCity()        Sets the current record's "City" collection
 * @method Country             setJob()         Sets the current record's "Job" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('idcountry', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('namecountry', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('City', array(
             'local' => 'idcountry',
             'foreign' => 'idcountry'));

        $this->hasMany('Job', array(
             'local' => 'idcountry',
             'foreign' => 'idcountry'));
    }
}