<?php

/**
 * BaseCategoryidea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Hotideas
 * 
 * @method string              getTitle()    Returns the current record's "title" value
 * @method Doctrine_Collection getHotideas() Returns the current record's "Hotideas" collection
 * @method Categoryidea        setTitle()    Sets the current record's "title" value
 * @method Categoryidea        setHotideas() Sets the current record's "Hotideas" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryidea extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoryidea');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Hotideas', array(
             'local' => 'id',
             'foreign' => 'categoryidea'));
    }
}