<?php

/**
 * BaseForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property integer $rank
 * @property integer $category
 * @property date $created_at
 * @property date $updated_at
 * @property string $stripped_name
 * @property integer $latest_post
 * @property integer $nb_posts
 * @property integer $nb_topics
 * 
 * @method string  getTitle()         Returns the current record's "title" value
 * @method clob    getDescription()   Returns the current record's "description" value
 * @method integer getRank()          Returns the current record's "rank" value
 * @method integer getCategory()      Returns the current record's "category" value
 * @method date    getCreatedAt()     Returns the current record's "created_at" value
 * @method date    getUpdatedAt()     Returns the current record's "updated_at" value
 * @method string  getStrippedName()  Returns the current record's "stripped_name" value
 * @method integer getLatestPost()    Returns the current record's "latest_post" value
 * @method integer getNbPosts()       Returns the current record's "nb_posts" value
 * @method integer getNbTopics()      Returns the current record's "nb_topics" value
 * @method Forum   setTitle()         Sets the current record's "title" value
 * @method Forum   setDescription()   Sets the current record's "description" value
 * @method Forum   setRank()          Sets the current record's "rank" value
 * @method Forum   setCategory()      Sets the current record's "category" value
 * @method Forum   setCreatedAt()     Sets the current record's "created_at" value
 * @method Forum   setUpdatedAt()     Sets the current record's "updated_at" value
 * @method Forum   setStrippedName()  Sets the current record's "stripped_name" value
 * @method Forum   setLatestPost()    Sets the current record's "latest_post" value
 * @method Forum   setNbPosts()       Sets the current record's "nb_posts" value
 * @method Forum   setNbTopics()      Sets the current record's "nb_topics" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForum extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('updated_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('stripped_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('latest_post', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_posts', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nb_topics', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}