<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subjobcategory', 'doctrine');

/**
 * BaseSubjobcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idsubjobcategory
 * @property integer $idjobcategory
 * @property string $titlesubjobcategory
 * @property Jobcategory $Jobcategory
 * @property Doctrine_Collection $Job
 * 
 * @method integer             getIdsubjobcategory()    Returns the current record's "idsubjobcategory" value
 * @method integer             getIdjobcategory()       Returns the current record's "idjobcategory" value
 * @method string              getTitlesubjobcategory() Returns the current record's "titlesubjobcategory" value
 * @method Jobcategory         getJobcategory()         Returns the current record's "Jobcategory" value
 * @method Doctrine_Collection getJob()                 Returns the current record's "Job" collection
 * @method Subjobcategory      setIdsubjobcategory()    Sets the current record's "idsubjobcategory" value
 * @method Subjobcategory      setIdjobcategory()       Sets the current record's "idjobcategory" value
 * @method Subjobcategory      setTitlesubjobcategory() Sets the current record's "titlesubjobcategory" value
 * @method Subjobcategory      setJobcategory()         Sets the current record's "Jobcategory" value
 * @method Subjobcategory      setJob()                 Sets the current record's "Job" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubjobcategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subjobcategory');
        $this->hasColumn('idsubjobcategory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idjobcategory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titlesubjobcategory', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jobcategory', array(
             'local' => 'idjobcategory',
             'foreign' => 'idjobcategory'));

        $this->hasMany('Job', array(
             'local' => 'idsubjobcategory',
             'foreign' => 'idsubjobcategory'));
    }
}