<?php

/**
 * BaseJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $city
 * @property date $dateperemption
 * @property integer $country
 * @property integer $author
 * @property integer $subjobcategory
 * @property Subjobcategory $Subjobcategory
 * @property Country $Country
 * @property DmUser $Author
 * 
 * @method string         getTitle()          Returns the current record's "title" value
 * @method clob           getDescription()    Returns the current record's "description" value
 * @method string         getCity()           Returns the current record's "city" value
 * @method date           getDateperemption() Returns the current record's "dateperemption" value
 * @method integer        getCountry()        Returns the current record's "country" value
 * @method integer        getAuthor()         Returns the current record's "author" value
 * @method integer        getSubjobcategory() Returns the current record's "subjobcategory" value
 * @method Subjobcategory getSubjobcategory() Returns the current record's "Subjobcategory" value
 * @method Country        getCountry()        Returns the current record's "Country" value
 * @method DmUser         getAuthor()         Returns the current record's "Author" value
 * @method Job            setTitle()          Sets the current record's "title" value
 * @method Job            setDescription()    Sets the current record's "description" value
 * @method Job            setCity()           Sets the current record's "city" value
 * @method Job            setDateperemption() Sets the current record's "dateperemption" value
 * @method Job            setCountry()        Sets the current record's "country" value
 * @method Job            setAuthor()         Sets the current record's "author" value
 * @method Job            setSubjobcategory() Sets the current record's "subjobcategory" value
 * @method Job            setSubjobcategory() Sets the current record's "Subjobcategory" value
 * @method Job            setCountry()        Sets the current record's "Country" value
 * @method Job            setAuthor()         Sets the current record's "Author" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJob extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('city', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('dateperemption', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('country', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subjobcategory', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subjobcategory', array(
             'local' => 'subjobcategory',
             'foreign' => 'id'));

        $this->hasOne('Country', array(
             'local' => 'country',
             'foreign' => 'id'));

        $this->hasOne('DmUser as Author', array(
             'local' => 'author',
             'foreign' => 'id'));
    }
}