<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cv', 'doctrine');

/**
 * BaseCv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cv
 * @property integer $iduser
 * @property string $titrecv
 * @property string $descriptioncv
 * @property date $datedisponibilitecv
 * @property string $tarifcv
 * @property integer $estvisiblecv
 * @property User $User
 * @property Doctrine_Collection $Experience
 * 
 * @method integer             getIdCv()                Returns the current record's "id_cv" value
 * @method integer             getIduser()              Returns the current record's "iduser" value
 * @method string              getTitrecv()             Returns the current record's "titrecv" value
 * @method string              getDescriptioncv()       Returns the current record's "descriptioncv" value
 * @method date                getDatedisponibilitecv() Returns the current record's "datedisponibilitecv" value
 * @method string              getTarifcv()             Returns the current record's "tarifcv" value
 * @method integer             getEstvisiblecv()        Returns the current record's "estvisiblecv" value
 * @method User                getUser()                Returns the current record's "User" value
 * @method Doctrine_Collection getExperience()          Returns the current record's "Experience" collection
 * @method Cv                  setIdCv()                Sets the current record's "id_cv" value
 * @method Cv                  setIduser()              Sets the current record's "iduser" value
 * @method Cv                  setTitrecv()             Sets the current record's "titrecv" value
 * @method Cv                  setDescriptioncv()       Sets the current record's "descriptioncv" value
 * @method Cv                  setDatedisponibilitecv() Sets the current record's "datedisponibilitecv" value
 * @method Cv                  setTarifcv()             Sets the current record's "tarifcv" value
 * @method Cv                  setEstvisiblecv()        Sets the current record's "estvisiblecv" value
 * @method Cv                  setUser()                Sets the current record's "User" value
 * @method Cv                  setExperience()          Sets the current record's "Experience" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cv');
        $this->hasColumn('id_cv', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titrecv', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descriptioncv', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('datedisponibilitecv', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tarifcv', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('estvisiblecv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'iduser',
             'foreign' => 'iduser'));

        $this->hasMany('Experience', array(
             'local' => 'id_cv',
             'foreign' => 'id_cv'));
    }
}