<?php

/**
 * BaseCv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property date $datedisponibilite
 * @property integer $user
 * @property string $tarif
 * @property boolean $isvisible
 * @property boolean $isdisponible
 * @property DmUser $User
 * @property Doctrine_Collection $Experience
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method clob                getDescription()       Returns the current record's "description" value
 * @method date                getDatedisponibilite() Returns the current record's "datedisponibilite" value
 * @method integer             getUser()              Returns the current record's "user" value
 * @method string              getTarif()             Returns the current record's "tarif" value
 * @method boolean             getIsvisible()         Returns the current record's "isvisible" value
 * @method boolean             getIsdisponible()      Returns the current record's "isdisponible" value
 * @method DmUser              getUser()              Returns the current record's "User" value
 * @method Doctrine_Collection getExperience()        Returns the current record's "Experience" collection
 * @method Cv                  setTitle()             Sets the current record's "title" value
 * @method Cv                  setDescription()       Sets the current record's "description" value
 * @method Cv                  setDatedisponibilite() Sets the current record's "datedisponibilite" value
 * @method Cv                  setUser()              Sets the current record's "user" value
 * @method Cv                  setTarif()             Sets the current record's "tarif" value
 * @method Cv                  setIsvisible()         Sets the current record's "isvisible" value
 * @method Cv                  setIsdisponible()      Sets the current record's "isdisponible" value
 * @method Cv                  setUser()              Sets the current record's "User" value
 * @method Cv                  setExperience()        Sets the current record's "Experience" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCv extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cv');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('datedisponibilite', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tarif', 'string', 120, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 120,
             ));
        $this->hasColumn('isvisible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('isdisponible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser as User', array(
             'local' => 'user',
             'foreign' => 'id'));

        $this->hasMany('Experience', array(
             'local' => 'id',
             'foreign' => 'cv'));
    }
}