<?php

/**
 * BaseConfidentialitylevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string100) $title
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfidentialitylevel extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('confidentialitylevel');
        $this->hasColumn('title', 'string100)', null, array(
             'type' => 'string100)',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}