<?php

/**
 * BaseForumtopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property boolean $is_sticked
 * @property boolean $is_locked
 * @property integer $forum
 * @property date $created_at
 * @property date $updated_at
 * @property integer $latest_post
 * @property integer $author
 * @property string $stripped_title
 * @property integer $nb_posts
 * @property integer $nb_views
 * 
 * @method string     getTitle()          Returns the current record's "title" value
 * @method boolean    getIsSticked()      Returns the current record's "is_sticked" value
 * @method boolean    getIsLocked()       Returns the current record's "is_locked" value
 * @method integer    getForum()          Returns the current record's "forum" value
 * @method date       getCreatedAt()      Returns the current record's "created_at" value
 * @method date       getUpdatedAt()      Returns the current record's "updated_at" value
 * @method integer    getLatestPost()     Returns the current record's "latest_post" value
 * @method integer    getAuthor()         Returns the current record's "author" value
 * @method string     getStrippedTitle()  Returns the current record's "stripped_title" value
 * @method integer    getNbPosts()        Returns the current record's "nb_posts" value
 * @method integer    getNbViews()        Returns the current record's "nb_views" value
 * @method Forumtopic setTitle()          Sets the current record's "title" value
 * @method Forumtopic setIsSticked()      Sets the current record's "is_sticked" value
 * @method Forumtopic setIsLocked()       Sets the current record's "is_locked" value
 * @method Forumtopic setForum()          Sets the current record's "forum" value
 * @method Forumtopic setCreatedAt()      Sets the current record's "created_at" value
 * @method Forumtopic setUpdatedAt()      Sets the current record's "updated_at" value
 * @method Forumtopic setLatestPost()     Sets the current record's "latest_post" value
 * @method Forumtopic setAuthor()         Sets the current record's "author" value
 * @method Forumtopic setStrippedTitle()  Sets the current record's "stripped_title" value
 * @method Forumtopic setNbPosts()        Sets the current record's "nb_posts" value
 * @method Forumtopic setNbViews()        Sets the current record's "nb_views" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumtopic extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forumtopic');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_sticked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_locked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('forum', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('updated_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('latest_post', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stripped_title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nb_posts', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('nb_views', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}