<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usertype', 'doctrine');

/**
 * BaseUsertype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusertype
 * @property string $nameusertype
 * @property integer $totalsupplierusertype
 * @property Doctrine_Collection $User
 * 
 * @method integer             getIdusertype()            Returns the current record's "idusertype" value
 * @method string              getNameusertype()          Returns the current record's "nameusertype" value
 * @method integer             getTotalsupplierusertype() Returns the current record's "totalsupplierusertype" value
 * @method Doctrine_Collection getUser()                  Returns the current record's "User" collection
 * @method Usertype            setIdusertype()            Sets the current record's "idusertype" value
 * @method Usertype            setNameusertype()          Sets the current record's "nameusertype" value
 * @method Usertype            setTotalsupplierusertype() Sets the current record's "totalsupplierusertype" value
 * @method Usertype            setUser()                  Sets the current record's "User" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsertype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usertype');
        $this->hasColumn('idusertype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nameusertype', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('totalsupplierusertype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'idusertype',
             'foreign' => 'idusertype'));
    }
}