<?php

/**
 * BaseForumcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $strippedname
 * @property clob $description
 * @property integer $rank
 * @property date $created_at
 * 
 * @method string        getTitle()        Returns the current record's "title" value
 * @method string        getStrippedname() Returns the current record's "strippedname" value
 * @method clob          getDescription()  Returns the current record's "description" value
 * @method integer       getRank()         Returns the current record's "rank" value
 * @method date          getCreatedAt()    Returns the current record's "created_at" value
 * @method Forumcategory setTitle()        Sets the current record's "title" value
 * @method Forumcategory setStrippedname() Sets the current record's "strippedname" value
 * @method Forumcategory setDescription()  Sets the current record's "description" value
 * @method Forumcategory setRank()         Sets the current record's "rank" value
 * @method Forumcategory setCreatedAt()    Sets the current record's "created_at" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumcategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forumcategory');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('strippedname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}