<?php

/**
 * BaseJobcategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Subjobcategory
 * 
 * @method string              getTitle()          Returns the current record's "title" value
 * @method Doctrine_Collection getSubjobcategory() Returns the current record's "Subjobcategory" collection
 * @method Jobcategory         setTitle()          Sets the current record's "title" value
 * @method Jobcategory         setSubjobcategory() Sets the current record's "Subjobcategory" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobcategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobcategory');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subjobcategory', array(
             'local' => 'id',
             'foreign' => 'jobcategory'));
    }
}