<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('City', 'doctrine');

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_city
 * @property integer $idcountry
 * @property string $cityname
 * @property Country $Country
 * @property Doctrine_Collection $Job
 * 
 * @method integer             getIdCity()    Returns the current record's "id_city" value
 * @method integer             getIdcountry() Returns the current record's "idcountry" value
 * @method string              getCityname()  Returns the current record's "cityname" value
 * @method Country             getCountry()   Returns the current record's "Country" value
 * @method Doctrine_Collection getJob()       Returns the current record's "Job" collection
 * @method City                setIdCity()    Sets the current record's "id_city" value
 * @method City                setIdcountry() Sets the current record's "idcountry" value
 * @method City                setCityname()  Sets the current record's "cityname" value
 * @method City                setCountry()   Sets the current record's "Country" value
 * @method City                setJob()       Sets the current record's "Job" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('id_city', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idcountry', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cityname', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'idcountry',
             'foreign' => 'idcountry'));

        $this->hasMany('Job', array(
             'local' => 'id_city',
             'foreign' => 'id_city'));
    }
}