<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Catgeoryidea', 'doctrine');

/**
 * BaseCatgeoryidea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcatgeoryidea
 * @property string $nom_catgeoryidea
 * @property Doctrine_Collection $Ideas
 * 
 * @method integer             getIdcatgeoryidea()   Returns the current record's "idcatgeoryidea" value
 * @method string              getNomCatgeoryidea()  Returns the current record's "nom_catgeoryidea" value
 * @method Doctrine_Collection getIdeas()            Returns the current record's "Ideas" collection
 * @method Catgeoryidea        setIdcatgeoryidea()   Sets the current record's "idcatgeoryidea" value
 * @method Catgeoryidea        setNomCatgeoryidea()  Sets the current record's "nom_catgeoryidea" value
 * @method Catgeoryidea        setIdeas()            Sets the current record's "Ideas" collection
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     OUTTRABADY Lucky
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCatgeoryidea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catgeoryidea');
        $this->hasColumn('idcatgeoryidea', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom_catgeoryidea', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ideas', array(
             'local' => 'idcatgeoryidea',
             'foreign' => 'idcatgeoryidea'));
    }
}