<?php

/**
 * BaseForumpost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $content
 * @property integer $topic
 * @property integer $author
 * @property date $created_at
 * @property integer $forum
 * @property string $author_name
 * 
 * @method string    getTitle()       Returns the current record's "title" value
 * @method clob      getContent()     Returns the current record's "content" value
 * @method integer   getTopic()       Returns the current record's "topic" value
 * @method integer   getAuthor()      Returns the current record's "author" value
 * @method date      getCreatedAt()   Returns the current record's "created_at" value
 * @method integer   getForum()       Returns the current record's "forum" value
 * @method string    getAuthorName()  Returns the current record's "author_name" value
 * @method Forumpost setTitle()       Sets the current record's "title" value
 * @method Forumpost setContent()     Sets the current record's "content" value
 * @method Forumpost setTopic()       Sets the current record's "topic" value
 * @method Forumpost setAuthor()      Sets the current record's "author" value
 * @method Forumpost setCreatedAt()   Sets the current record's "created_at" value
 * @method Forumpost setForum()       Sets the current record's "forum" value
 * @method Forumpost setAuthorName()  Sets the current record's "author_name" value
 * 
 * @package    ConsultingCoffee
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumpost extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forumpost');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('topic', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('forum', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}