<?php
// auto-generated by dmModuleManagerConfigHandler
// date: 2011/06/23 19:13:04
$manager = new dmModuleManager();
$modules = $projectModules = $modelModules = $types = array();
$types['Content'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Feedback'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmContact'] = $projectModules['dmContact'] = $spaceModules['dmContact'] = new dmProjectModule('dmContact', $typeSpaces['Feedback'], array (
  'name' => 'Contact',
  'plural' => 'Contacts',
  'model' => 'DmContact',
  'credentials' => NULL,
  'underscore' => 'dm_contact',
  'plugin' => 'dmContactPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), ),
  'parent_key' => NULL,
  'has_page' => false,
  'sf_name' => 'dmContactAdmin',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['DmContact'] = 'dmContact';
$typeSpaces['Feedback']->initialize('Feedback', $types['Content'], $spaceModules);
unset($spaceModules);
$typeSpaces['Global'] = new dmModuleSpace();
$spaceModules = array();
$modules['main'] = $projectModules['main'] = $spaceModules['main'] = new dmProjectModule('main', $typeSpaces['Global'], array (
  'name' => 'Main',
  'plural' => 'Main',
  'model' => false,
  'credentials' => NULL,
  'underscore' => 'main',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => array('header' => new dmModuleComponent('header', array (
  'name' => 'Header',
  'type' => 'simple',
)), 'footer' => new dmModuleComponent('footer', array (
  'name' => 'Footer',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => false,
  'sf_name' => 'main',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modules['dmUser'] = $projectModules['dmUser'] = $spaceModules['dmUser'] = new dmProjectModule('dmUser', $typeSpaces['Global'], array (
  'name' => 'User',
  'plural' => 'Users',
  'model' => 'DmUser',
  'credentials' => 'security_user',
  'underscore' => 'dm_user',
  'plugin' => 'dmUserPlugin',
  'overridden' => true,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('signin' => new dmModuleComponent('signin', array (
  'name' => 'Signin',
  'type' => 'simple',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Register',
  'type' => 'form',
)), 'editProfil' => new dmModuleComponent('editProfil', array (
  'name' => 'Edit profil',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => false,
  'sf_name' => 'dmUserAdmin',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['DmUser'] = 'dmUser';
$typeSpaces['Global']->initialize('Global', $types['Content'], $spaceModules);
unset($spaceModules);
$types['Content']->initialize('Content', $typeSpaces);
unset($typeSpaces);
$types['Internal'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Page'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmPageView'] = $spaceModules['dmPageView'] = new dmModule('dmPageView', $typeSpaces['Page'], array (
  'name' => 'Dm page view',
  'plural' => 'Dm page views',
  'model' => 'DmPageView',
  'credentials' => NULL,
  'underscore' => 'dm_page_view',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmPageViewAdmin',
));
$modelModules['DmPageView'] = 'dmPageView';
$modules['dmArea'] = $spaceModules['dmArea'] = new dmModule('dmArea', $typeSpaces['Page'], array (
  'name' => 'Dm area',
  'plural' => 'Dm areas',
  'model' => 'DmArea',
  'credentials' => NULL,
  'underscore' => 'dm_area',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmAreaAdmin',
));
$modelModules['DmArea'] = 'dmArea';
$modules['dmZone'] = $spaceModules['dmZone'] = new dmModule('dmZone', $typeSpaces['Page'], array (
  'name' => 'Dm zone',
  'plural' => 'Dm zones',
  'model' => 'DmZone',
  'credentials' => NULL,
  'underscore' => 'dm_zone',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmZoneAdmin',
));
$modelModules['DmZone'] = 'dmZone';
$modules['dmWidget'] = $spaceModules['dmWidget'] = new dmModule('dmWidget', $typeSpaces['Page'], array (
  'name' => 'Dm widget',
  'plural' => 'Dm widgets',
  'model' => 'DmWidget',
  'credentials' => NULL,
  'underscore' => 'dm_widget',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmWidgetAdmin',
));
$modelModules['DmWidget'] = 'dmWidget';
$typeSpaces['Page']->initialize('Page', $types['Internal'], $spaceModules);
unset($spaceModules);
$types['Internal']->initialize('Internal', $typeSpaces);
unset($typeSpaces);
$types['System'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Security'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmPermission'] = $spaceModules['dmPermission'] = new dmModule('dmPermission', $typeSpaces['Security'], array (
  'name' => 'Permission',
  'plural' => 'Permissions',
  'model' => 'DmPermission',
  'credentials' => 'security_permission',
  'underscore' => 'dm_permission',
  'plugin' => 'dmUserPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmPermissionAdmin',
));
$modelModules['DmPermission'] = 'dmPermission';
$modules['dmGroup'] = $spaceModules['dmGroup'] = new dmModule('dmGroup', $typeSpaces['Security'], array (
  'name' => 'Group',
  'plural' => 'Groups',
  'model' => 'DmGroup',
  'credentials' => 'security_group',
  'underscore' => 'dm_group',
  'plugin' => 'dmUserPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmGroupAdmin',
));
$modelModules['DmGroup'] = 'dmGroup';
$typeSpaces['Security']->initialize('Security', $types['System'], $spaceModules);
unset($spaceModules);
$typeSpaces['Configuration'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmSetting'] = $spaceModules['dmSetting'] = new dmModule('dmSetting', $typeSpaces['Configuration'], array (
  'name' => 'Setting',
  'plural' => 'Settings',
  'model' => 'DmSetting',
  'credentials' => 'system',
  'underscore' => 'dm_setting',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmSetting',
));
$modelModules['DmSetting'] = 'dmSetting';
$typeSpaces['Configuration']->initialize('Configuration', $types['System'], $spaceModules);
unset($spaceModules);
$typeSpaces['Log'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmSentMail'] = $spaceModules['dmSentMail'] = new dmModule('dmSentMail', $typeSpaces['Log'], array (
  'name' => 'Sent mail',
  'plural' => 'Sent mails',
  'model' => 'DmSentMail',
  'credentials' => 'sent_mail',
  'underscore' => 'dm_sent_mail',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmSentMail',
));
$modelModules['DmSentMail'] = 'dmSentMail';
$modules['dmError'] = $spaceModules['dmError'] = new dmModule('dmError', $typeSpaces['Log'], array (
  'name' => 'Error',
  'plural' => 'Errors',
  'model' => 'DmError',
  'credentials' => 'error_log',
  'underscore' => 'dm_error',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmError',
));
$modelModules['DmError'] = 'dmError';
$typeSpaces['Log']->initialize('Log', $types['System'], $spaceModules);
unset($spaceModules);
$typeSpaces['Dev'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmDiagram'] = $spaceModules['dmDiagram'] = new dmModule('dmDiagram', $typeSpaces['Dev'], array (
  'name' => 'See diagrams',
  'plural' => 'See diagrams',
  'model' => false,
  'credentials' => 'see_diagrams',
  'underscore' => 'dm_diagram',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmDiagram',
));
$modules['dmCodeEditor'] = $spaceModules['dmCodeEditor'] = new dmModule('dmCodeEditor', $typeSpaces['Dev'], array (
  'name' => 'Code Editor',
  'plural' => 'Code Editor',
  'model' => false,
  'credentials' => 'code_editor',
  'underscore' => 'dm_code_editor',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmCodeEditor',
));
$modules['dmConsole'] = $spaceModules['dmConsole'] = new dmModule('dmConsole', $typeSpaces['Dev'], array (
  'name' => 'Diem Console',
  'plural' => 'Diem Console',
  'model' => false,
  'credentials' => 'system',
  'underscore' => 'dm_console',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmConsole',
));
$modules['dmServer'] = $spaceModules['dmServer'] = new dmModule('dmServer', $typeSpaces['Dev'], array (
  'name' => 'Server',
  'plural' => 'Server',
  'model' => false,
  'credentials' => 'see_server',
  'underscore' => 'dm_server',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmServer',
));
$typeSpaces['Dev']->initialize('Dev', $types['System'], $spaceModules);
unset($spaceModules);
$types['System']->initialize('System', $typeSpaces);
unset($typeSpaces);
$types['Tools'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Configuration'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmConfigPanel'] = $spaceModules['dmConfigPanel'] = new dmModule('dmConfigPanel', $typeSpaces['Configuration'], array (
  'name' => 'Configuration panel',
  'plural' => 'Configuration panel',
  'model' => false,
  'credentials' => 'config_panel',
  'underscore' => 'dm_config_panel',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmConfigPanel',
));
$modules['dmMailTemplate'] = $spaceModules['dmMailTemplate'] = new dmModule('dmMailTemplate', $typeSpaces['Configuration'], array (
  'name' => 'Mail template',
  'plural' => 'Mail templates',
  'model' => 'DmMailTemplate',
  'credentials' => 'mail_template',
  'underscore' => 'dm_mail_template',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmMailTemplate',
));
$modelModules['DmMailTemplate'] = 'dmMailTemplate';
$modules['dmLayout'] = $spaceModules['dmLayout'] = new dmModule('dmLayout', $typeSpaces['Configuration'], array (
  'name' => 'Layout',
  'plural' => 'Layouts',
  'model' => 'DmLayout',
  'credentials' => 'layout',
  'underscore' => 'dm_layout',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmLayout',
));
$modelModules['DmLayout'] = 'dmLayout';
$typeSpaces['Configuration']->initialize('Configuration', $types['Tools'], $spaceModules);
unset($spaceModules);
$typeSpaces['Translation'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmTransUnit'] = $spaceModules['dmTransUnit'] = new dmModule('dmTransUnit', $typeSpaces['Translation'], array (
  'name' => 'Sentence',
  'plural' => 'Sentences',
  'model' => 'DmTransUnit',
  'credentials' => 'translation',
  'underscore' => 'dm_trans_unit',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmTransUnit',
));
$modelModules['DmTransUnit'] = 'dmTransUnit';
$typeSpaces['Translation']->initialize('Translation', $types['Tools'], $spaceModules);
unset($spaceModules);
$typeSpaces['Monitoring'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmChart'] = $spaceModules['dmChart'] = new dmModule('dmChart', $typeSpaces['Monitoring'], array (
  'name' => 'Chart',
  'plural' => 'Chart',
  'model' => false,
  'credentials' => 'see_chart',
  'underscore' => 'dm_chart',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmChart',
));
$modules['dmLog'] = $spaceModules['dmLog'] = new dmModule('dmLog', $typeSpaces['Monitoring'], array (
  'name' => 'Log',
  'plural' => 'Log',
  'model' => false,
  'credentials' => 'see_log',
  'underscore' => 'dm_log',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmLog',
));
$typeSpaces['Monitoring']->initialize('Monitoring', $types['Tools'], $spaceModules);
unset($spaceModules);
$typeSpaces['Media'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmMediaLibrary'] = $spaceModules['dmMediaLibrary'] = new dmModule('dmMediaLibrary', $typeSpaces['Media'], array (
  'name' => 'Media',
  'plural' => 'Media',
  'model' => false,
  'credentials' => 'media_library',
  'underscore' => 'dm_media_library',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmMediaLibrary',
));
$typeSpaces['Media']->initialize('Media', $types['Tools'], $spaceModules);
unset($spaceModules);
$typeSpaces['Search engine'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmSearchEngine'] = $spaceModules['dmSearchEngine'] = new dmModule('dmSearchEngine', $typeSpaces['Search engine'], array (
  'name' => 'Manage index',
  'plural' => 'Manage index',
  'model' => false,
  'credentials' => 'search_engine',
  'underscore' => 'dm_search_engine',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmSearchEngine',
));
$typeSpaces['Search engine']->initialize('Search engine', $types['Tools'], $spaceModules);
unset($spaceModules);
$types['Tools']->initialize('Tools', $typeSpaces);
unset($typeSpaces);
$types['Seo'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Services'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmGoogleAnalytics'] = $spaceModules['dmGoogleAnalytics'] = new dmModule('dmGoogleAnalytics', $typeSpaces['Services'], array (
  'name' => 'Google analytics',
  'plural' => 'Google analytics',
  'model' => false,
  'credentials' => 'use_google_analytics',
  'underscore' => 'dm_google_analytics',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmGoogleAnalytics',
));
$modules['dmGoogleWebmasterTools'] = $spaceModules['dmGoogleWebmasterTools'] = new dmModule('dmGoogleWebmasterTools', $typeSpaces['Services'], array (
  'name' => 'Google webmaster tools',
  'plural' => 'Google webmaster tools',
  'model' => false,
  'credentials' => 'use_google_webmaster_tools',
  'underscore' => 'dm_google_webmaster_tools',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmGoogleWebmasterTools',
));
$typeSpaces['Services']->initialize('Services', $types['Seo'], $spaceModules);
unset($spaceModules);
$typeSpaces['Sitemap'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmSitemap'] = $spaceModules['dmSitemap'] = new dmModule('dmSitemap', $typeSpaces['Sitemap'], array (
  'name' => 'Manage XML sitemap',
  'plural' => 'Manage XML sitemap',
  'model' => false,
  'credentials' => 'sitemap',
  'underscore' => 'dm_sitemap',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmSitemap',
));
$typeSpaces['Sitemap']->initialize('Sitemap', $types['Seo'], $spaceModules);
unset($spaceModules);
$typeSpaces['Pages'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmPage'] = $spaceModules['dmPage'] = new dmModule('dmPage', $typeSpaces['Pages'], array (
  'name' => 'Manage pages',
  'plural' => 'Manage pages',
  'model' => 'DmPage',
  'credentials' => 'manage_pages, manual_metas',
  'underscore' => 'dm_page',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmPage',
));
$modelModules['DmPage'] = 'dmPage';
$modules['dmAutoSeo'] = $spaceModules['dmAutoSeo'] = new dmModule('dmAutoSeo', $typeSpaces['Pages'], array (
  'name' => 'Automatic SEO',
  'plural' => 'Automatic SEO',
  'model' => 'DmAutoSeo',
  'credentials' => 'automatic_metas',
  'underscore' => 'dm_auto_seo',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmAutoSeo',
));
$modelModules['DmAutoSeo'] = 'dmAutoSeo';
$typeSpaces['Pages']->initialize('Pages', $types['Seo'], $spaceModules);
unset($spaceModules);
$typeSpaces['Redirections'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmRedirect'] = $spaceModules['dmRedirect'] = new dmModule('dmRedirect', $typeSpaces['Redirections'], array (
  'name' => 'Url Redirections',
  'plural' => 'Url Redirections',
  'model' => 'DmRedirect',
  'credentials' => 'url_redirection',
  'underscore' => 'dm_redirect',
  'plugin' => 'dmAdminPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmRedirect',
));
$modelModules['DmRedirect'] = 'dmRedirect';
$typeSpaces['Redirections']->initialize('Redirections', $types['Seo'], $spaceModules);
unset($spaceModules);
$types['Seo']->initialize('Seo', $typeSpaces);
unset($typeSpaces);
$types['Parameters'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Parameters'] = new dmModuleSpace();
$spaceModules = array();
$modules['categoryidea'] = $spaceModules['categoryidea'] = new dmModule('categoryidea', $typeSpaces['Parameters'], array (
  'name' => 'Categoryidea',
  'plural' => 'Categoryideas',
  'model' => 'Categoryidea',
  'credentials' => NULL,
  'underscore' => 'categoryidea',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'categoryidea',
));
$modelModules['Categoryidea'] = 'categoryidea';
$modules['expertise'] = $spaceModules['expertise'] = new dmModule('expertise', $typeSpaces['Parameters'], array (
  'name' => 'Expertise',
  'plural' => 'Expertises',
  'model' => 'Expertise',
  'credentials' => NULL,
  'underscore' => 'expertise',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'expertise',
));
$modelModules['Expertise'] = 'expertise';
$modules['usertype'] = $spaceModules['usertype'] = new dmModule('usertype', $typeSpaces['Parameters'], array (
  'name' => 'Usertype',
  'plural' => 'Usertypes',
  'model' => 'Usertype',
  'credentials' => NULL,
  'underscore' => 'usertype',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'usertype',
));
$modelModules['Usertype'] = 'usertype';
$modules['jobcategory'] = $spaceModules['jobcategory'] = new dmModule('jobcategory', $typeSpaces['Parameters'], array (
  'name' => 'Jobcategory',
  'plural' => 'Jobcategorys',
  'model' => 'Jobcategory',
  'credentials' => NULL,
  'underscore' => 'jobcategory',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'jobcategory',
));
$modelModules['Jobcategory'] = 'jobcategory';
$modules['confidentialitylevel'] = $spaceModules['confidentialitylevel'] = new dmModule('confidentialitylevel', $typeSpaces['Parameters'], array (
  'name' => 'Confidentialitylevel',
  'plural' => 'Confidentialitylevels',
  'model' => 'Confidentialitylevel',
  'credentials' => NULL,
  'underscore' => 'confidentialitylevel',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'confidentialitylevel',
));
$modelModules['Confidentialitylevel'] = 'confidentialitylevel';
$modules['subjobcategory'] = $spaceModules['subjobcategory'] = new dmModule('subjobcategory', $typeSpaces['Parameters'], array (
  'name' => 'Subjobcategory',
  'plural' => 'Subjobcategorys',
  'model' => 'Subjobcategory',
  'credentials' => NULL,
  'underscore' => 'subjobcategory',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'subjobcategory',
));
$modelModules['Subjobcategory'] = 'subjobcategory';
$modules['sector'] = $spaceModules['sector'] = new dmModule('sector', $typeSpaces['Parameters'], array (
  'name' => 'Sector',
  'plural' => 'Sectors',
  'model' => 'Sector',
  'credentials' => NULL,
  'underscore' => 'sector',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'sector',
));
$modelModules['Sector'] = 'sector';
$modules['country'] = $spaceModules['country'] = new dmModule('country', $typeSpaces['Parameters'], array (
  'name' => 'Country',
  'plural' => 'Countrys',
  'model' => 'Country',
  'credentials' => NULL,
  'underscore' => 'country',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'country',
));
$modelModules['Country'] = 'country';
$typeSpaces['Parameters']->initialize('Parameters', $types['Parameters'], $spaceModules);
unset($spaceModules);
$types['Parameters']->initialize('Parameters', $typeSpaces);
unset($typeSpaces);
$types['Informations Users'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Informations'] = new dmModuleSpace();
$spaceModules = array();
$modules['cv'] = $projectModules['cv'] = $spaceModules['cv'] = new dmProjectModule('cv', $typeSpaces['Informations'], array (
  'name' => 'Cv',
  'plural' => 'Cvs',
  'model' => 'Cv',
  'credentials' => NULL,
  'underscore' => 'cv',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'listPersonal' => new dmModuleComponent('listPersonal', array (
  'name' => 'List personal',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'cv',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Cv'] = 'cv';
$modules['experience'] = $spaceModules['experience'] = new dmModule('experience', $typeSpaces['Informations'], array (
  'name' => 'Experience',
  'plural' => 'Experiences',
  'model' => 'Experience',
  'credentials' => NULL,
  'underscore' => 'experience',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'experience',
));
$modelModules['Experience'] = 'experience';
$modules['hotideas'] = $projectModules['hotideas'] = $spaceModules['hotideas'] = new dmProjectModule('hotideas', $typeSpaces['Informations'], array (
  'name' => 'Hotideas',
  'plural' => 'Hotideas',
  'model' => 'Hotideas',
  'credentials' => NULL,
  'underscore' => 'hotideas',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'listPersonal' => new dmModuleComponent('listPersonal', array (
  'name' => 'List personal',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'hotideas',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Hotideas'] = 'hotideas';
$modules['job'] = $projectModules['job'] = $spaceModules['job'] = new dmProjectModule('job', $typeSpaces['Informations'], array (
  'name' => 'Job',
  'plural' => 'Jobs',
  'model' => 'Job',
  'credentials' => NULL,
  'underscore' => 'job',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'listPersonal' => new dmModuleComponent('listPersonal', array (
  'name' => 'List personal',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'job',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Job'] = 'job';
$typeSpaces['Informations']->initialize('Informations', $types['Informations Users'], $spaceModules);
unset($spaceModules);
$types['Informations Users']->initialize('Informations Users', $typeSpaces);
unset($typeSpaces);
$types['Forum'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Forum block'] = new dmModuleSpace();
$spaceModules = array();
$modules['forumcategory'] = $projectModules['forumcategory'] = $spaceModules['forumcategory'] = new dmProjectModule('forumcategory', $typeSpaces['Forum block'], array (
  'name' => 'Forumcategory',
  'plural' => 'Forumcategorys',
  'model' => 'Forumcategory',
  'credentials' => NULL,
  'underscore' => 'forumcategory',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'forumcategory',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Forumcategory'] = 'forumcategory';
$modules['forum'] = $projectModules['forum'] = $spaceModules['forum'] = new dmProjectModule('forum', $typeSpaces['Forum block'], array (
  'name' => 'Forum',
  'plural' => 'Forums',
  'model' => 'Forum',
  'credentials' => NULL,
  'underscore' => 'forum',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'forum',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Forum'] = 'forum';
$modules['forumtopic'] = $projectModules['forumtopic'] = $spaceModules['forumtopic'] = new dmProjectModule('forumtopic', $typeSpaces['Forum block'], array (
  'name' => 'Forumtopic',
  'plural' => 'Forumtopics',
  'model' => 'Forumtopic',
  'credentials' => NULL,
  'underscore' => 'forumtopic',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'forumtopic',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['Forumtopic'] = 'forumtopic';
$modules['forumPost'] = $projectModules['forumPost'] = $spaceModules['forumPost'] = new dmProjectModule('forumPost', $typeSpaces['Forum block'], array (
  'name' => 'Forum post',
  'plural' => 'Forum posts',
  'model' => 'ForumPost',
  'credentials' => NULL,
  'underscore' => 'forum_post',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('list' => new dmModuleComponent('list', array (
  'name' => 'List',
  'type' => 'list',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Form',
  'type' => 'form',
)), 'show' => new dmModuleComponent('show', array (
  'name' => 'Show',
  'type' => 'show',
)), 'edit' => new dmModuleComponent('edit', array (
  'name' => 'Edit',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => true,
  'sf_name' => 'forumPost',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['ForumPost'] = 'forumPost';
$typeSpaces['Forum block']->initialize('Forum block', $types['Forum'], $spaceModules);
unset($spaceModules);
$types['Forum']->initialize('Forum', $typeSpaces);
unset($typeSpaces);
$manager->load($types, $modules, $projectModules, $modelModules);
unset($types, $modules, $projectModules, $modelModules);
return $manager;