<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/23 19:13:02
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_recaptcha_public_key' => NULL,
  'app_recaptcha_private_key' => NULL,
  'app_recaptcha_enabled' => false,
));
