<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/23 19:13:22
sfConfig::add(array(
  'mod_dmadmingenerator_enabled' => true,
  'mod_dmadmingenerator_view_class' => 'sfPHP',
));
