<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/23 19:13:05
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'moduleTypeSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'moduleSpaceSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'browserSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'moduleTypeSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout' ? false : 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('markdown', '', array ());
  $response->addStylesheet('admin.moduleSpace', '', array ());
  $response->addJavascript('admin', '', array ());
}
else if ($templateName.$this->viewName == 'moduleSpaceSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout' ? false : 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('markdown', '', array ());
  $response->addStylesheet('admin.moduleSpace', '', array ());
  $response->addJavascript('admin', '', array ());
}
else if ($templateName.$this->viewName == 'browserSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout' ? false : 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('markdown', '', array ());
  $response->addStylesheet('browser', '', array ());
  $response->addJavascript('admin', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout' ? false : 'C:\development\sfprojects\ConsultingCoffee\lib\vendor\diem/dmAdminPlugin/modules/dmAdmin/templates/layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('markdown', '', array ());
  $response->addJavascript('admin', '', array ());
}

