<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 19:13:22
$this->security = array (
  'savesort' => 
  array (
    'credentials' => 
    array (
      0 => 'content',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
