<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 19:13:28
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'security_user',
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'myaccount' => 
  array (
    'credentials' => 'admin',
  ),
);
