<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 19:13:08
$this->security = array (
  'refresh' => 
  array (
    'is_secure' => true,
    'credential' => 'clear_cache',
  ),
  'refreshstep' => 
  array (
    'is_secure' => true,
    'credential' => 'clear_cache',
  ),
  'markdown' => 
  array (
    'is_secure' => true,
    'credential' => 'admin',
  ),
  'thumbnail' => 
  array (
    'is_secure' => true,
    'credential' => 'admin',
  ),
  'ping' => 
  array (
    'is_secure' => true,
    'credential' => 'admin',
  ),
  'selectculture' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
