<?php

/**
 * AvenduTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvenduTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvenduTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Avendu');
    }
}