<?php

/**
 * ConfidentialitylevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfidentialitylevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfidentialitylevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Confidentialitylevel');
    }
}