<?php

/**
 * CvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cv');
    }
}