<?php

/**
 * DocumenttypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumenttypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumenttypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documenttype');
    }
}