<?php

/**
 * FormatlistacceptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatlistacceptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatlistacceptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formatlistaccept');
    }
}