<?php

/**
 * HaveexpertiseinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HaveexpertiseinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HaveexpertiseinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Haveexpertisein');
    }
}