<?php

/**
 * IdeasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ideas');
    }
}