<?php

/**
 * JobcategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jobcategory');
    }
}