<?php

/**
 * SectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sector');
    }
}