<?php

/**
 * SubjobcategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubjobcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubjobcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subjobcategory');
    }
}