<?php

/**
 * UsertypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsertypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsertypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usertype');
    }
}