<?php

/**
 * WorkinsectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkinsectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkinsectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Workinsector');
    }
}