<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/23 18:45:02
sfConfig::add(array(
  'dm_i18n_cultures' => array (
  0 => 'fr',
),
  'dm_i18n_catalogue' => 'front',
  'dm_cache_apc' => true,
  'dm_js_compress' => true,
  'dm_js_cdn' => array (
  'enabled' => false,
  'lib.jquery' => 'http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js',
),
  'dm_js_head_inclusion' => array (
),
  'dm_css_compress' => true,
  'dm_seo_use_keywords' => true,
  'dm_seo_truncate' => array (
  'slug' => 255,
  'name' => 255,
  'title' => 80,
  'h1' => 255,
  'description' => 160,
  'keywords' => 255,
),
  'dm_orm_identifier_fields' => array (
  0 => 'name',
  1 => 'title',
  2 => 'subject',
  3 => 'author',
  4 => 'id',
),
  'dm_orm_cache_enabled' => true,
  'dm_backup_enabled' => true,
  'dm_web_debug_only_html_response' => true,
  'dm_web_debug_config_fast_dump' => true,
  'dm_toolBar_flavour' => 'blue',
  'dm_media_default' => false,
  'dm_security_remember_cookie_name' => NULL,
  'dm_security_remember_key_expiration_age' => NULL,
  'dm_web_services_version_check' => true,
  'dm_web_services_report_anonymous_data' => false,
  'dm_locks_enabled' => true,
  'dm_locks_timeout' => 10,
  'dm_performance_enable_mailer' => true,
  'dm_performance_page_cache' => array (
  'enabled' => false,
  'life_time' => 86400,
),
  'dm_core_asset' => 'dmCorePlugin',
  'dm_admin_asset' => 'dmAdminPlugin',
  'dm_front_asset' => 'dmFrontPlugin',
  'dm_accessibility_image_empty_alts' => true,
  'dm_html_doctype' => array (
  'name' => 'html',
  'version' => 5,
  'compliance' => 'transitional',
),
  'dm_pageBar_enabled' => true,
  'dm_mediaBar_enabled' => true,
  'dm_service_container_base_class' => 'dmFrontBaseServiceContainer',
  'dm_theming_themes' => array (
  'Default' => 
  array (
    'name' => 'Cool Water',
    'dir' => 'themeCoolWater',
    'enabled' => true,
  ),
),
));
