<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 18:45:04
$this->security = array (
  'edittoggle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'tool_bar_front',
    ),
  ),
  'showtoolbartoggle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'tool_bar_front',
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
