<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 18:46:07
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'delete' => 
  array (
    'credentials' => 'page_delete',
  ),
  'new' => 
  array (
    'credentials' => 'page_add',
  ),
  'edit' => 
  array (
    'credentials' => 'page_edit',
  ),
);
