<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('cv', 'cv_user_dm_user_id', array(
             'name' => 'cv_user_dm_user_id',
             'local' => 'user',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             ));
        $this->addIndex('cv', 'cv_user', array(
             'fields' => 
             array(
              0 => 'user',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('cv', 'cv_user_dm_user_id');
        $this->removeIndex('cv', 'cv_user', array(
             'fields' => 
             array(
              0 => 'user',
             ),
             ));
    }
}