<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('job', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '10',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '120',
             ),
             'dateperemption' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'country' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'subjobcategory' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('job');
    }
}