<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('job', 'author', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('job', 'author');
    }
}