<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('job', 'job_subjobcategory_subjobcategory_id', array(
             'name' => 'job_subjobcategory_subjobcategory_id',
             'local' => 'subjobcategory',
             'foreign' => 'id',
             'foreignTable' => 'subjobcategory',
             ));
        $this->createForeignKey('job', 'job_country_country_id', array(
             'name' => 'job_country_country_id',
             'local' => 'country',
             'foreign' => 'id',
             'foreignTable' => 'country',
             ));
        $this->addIndex('job', 'job_subjobcategory', array(
             'fields' => 
             array(
              0 => 'subjobcategory',
             ),
             ));
        $this->addIndex('job', 'job_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('job', 'job_subjobcategory_subjobcategory_id');
        $this->dropForeignKey('job', 'job_country_country_id');
        $this->removeIndex('job', 'job_subjobcategory', array(
             'fields' => 
             array(
              0 => 'subjobcategory',
             ),
             ));
        $this->removeIndex('job', 'job_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }
}