<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('job', 'job_author_dm_user_id', array(
             'name' => 'job_author_dm_user_id',
             'local' => 'author',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             ));
        $this->addIndex('job', 'job_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('job', 'job_author_dm_user_id');
        $this->removeIndex('job', 'job_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
    }
}