<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('forum_category');
        $this->dropTable('forum_post');
        $this->dropTable('forum_topic');
        $this->dropTable('forum_topic_view');
        $this->createTable('forumcategory', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'strippedname' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'rank' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forumpost', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'topic' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'forum' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forumtopic', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'is_sticked' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'is_locked' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'forum' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'latest_post' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'stripped_title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'nb_posts' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             'nb_views' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forumtopicview', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'topic' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->createTable('forum_category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'strippedname' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'rank' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forum_post', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'content' => 
             array(
              'type' => 'clob',
              'extra' => 'markdown',
              'length' => '',
             ),
             'topic' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'forum' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forum_topic', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'is_sticked' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'is_locked' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'forum' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'latest_post' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'stripped_title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'nb_posts' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             'nb_views' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('forum_topic_view', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'author' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'topic' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('forumcategory');
        $this->dropTable('forumpost');
        $this->dropTable('forumtopic');
        $this->dropTable('forumtopicview');
    }
}