<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('experience', 'experience_cv_cv_id', array(
             'name' => 'experience_cv_cv_id',
             'local' => 'cv',
             'foreign' => 'id',
             'foreignTable' => 'cv',
             ));
        $this->addIndex('experience', 'experience_cv', array(
             'fields' => 
             array(
              0 => 'cv',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('experience', 'experience_cv_cv_id');
        $this->removeIndex('experience', 'experience_cv', array(
             'fields' => 
             array(
              0 => 'cv',
             ),
             ));
    }
}