<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dm_user', 'dm_user_photo_dm_media_id', array(
             'name' => 'dm_user_photo_dm_media_id',
             'local' => 'photo',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('dm_user', 'dm_user_sector_sector_id', array(
             'name' => 'dm_user_sector_sector_id',
             'local' => 'sector',
             'foreign' => 'id',
             'foreignTable' => 'sector',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('dm_user', 'dm_user_expertise_expertise_id', array(
             'name' => 'dm_user_expertise_expertise_id',
             'local' => 'expertise',
             'foreign' => 'id',
             'foreignTable' => 'expertise',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('dm_user', 'dm_user_usertype_usertype_id', array(
             'name' => 'dm_user_usertype_usertype_id',
             'local' => 'usertype',
             'foreign' => 'id',
             'foreignTable' => 'usertype',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('dm_user', 'dm_user_country_country_id', array(
             'name' => 'dm_user_country_country_id',
             'local' => 'country',
             'foreign' => 'id',
             'foreignTable' => 'country',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('dm_user', 'dm_user_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->addIndex('dm_user', 'dm_user_sector', array(
             'fields' => 
             array(
              0 => 'sector',
             ),
             ));
        $this->addIndex('dm_user', 'dm_user_expertise', array(
             'fields' => 
             array(
              0 => 'expertise',
             ),
             ));
        $this->addIndex('dm_user', 'dm_user_usertype', array(
             'fields' => 
             array(
              0 => 'usertype',
             ),
             ));
        $this->addIndex('dm_user', 'dm_user_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dm_user', 'dm_user_photo_dm_media_id');
        $this->dropForeignKey('dm_user', 'dm_user_sector_sector_id');
        $this->dropForeignKey('dm_user', 'dm_user_expertise_expertise_id');
        $this->dropForeignKey('dm_user', 'dm_user_usertype_usertype_id');
        $this->dropForeignKey('dm_user', 'dm_user_country_country_id');
        $this->removeIndex('dm_user', 'dm_user_photo', array(
             'fields' => 
             array(
              0 => 'photo',
             ),
             ));
        $this->removeIndex('dm_user', 'dm_user_sector', array(
             'fields' => 
             array(
              0 => 'sector',
             ),
             ));
        $this->removeIndex('dm_user', 'dm_user_expertise', array(
             'fields' => 
             array(
              0 => 'expertise',
             ),
             ));
        $this->removeIndex('dm_user', 'dm_user_usertype', array(
             'fields' => 
             array(
              0 => 'usertype',
             ),
             ));
        $this->removeIndex('dm_user', 'dm_user_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }
}