<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/15 09:54:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=consultingcoffee',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
