<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/15 12:27:20
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Consulting coffee', false, false);
  $response->addMeta('description', 'Even consultant need a little help!', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('style.ie7.css', '', array ());
  $response->addJavascript('script.js', '', array ());


