Categoryidea:
 columns:
  title:            { type: string(100), notnull: true }
Expertise:
 columns:
  title:            { type: string(100), notnull: true }
Sector:
 columns:
  title:            { type: string(100), notnull: true }
Usertype:
 columns:
  title:            { type: string(100), notnull: true }
Jobcategory:
 columns:
  title:            { type: string(100), notnull: true }
Country:
 columns:
  title:            { type: string(100), notnull: true }
Confidentialitylevel:
 columns:
  title:            { type: string100), notnull: true }
DmUser:  
  columns:  
    title:            { type: string(10), notnull: true }  
    firstname:        { type: string(100), notnull: true }  
    cellphonenumber:  { type: string(30), notnull: false }  
    fixephoneNumber:  { type: string(30), notnull: false }  
    faxNumber:        { type: string(30), notnull: false }  
    society:          { type: string(120), notnull: true }  
    adress:           { type: string(300), notnull: false }  
    zipcode:          { type: string(20), notnull: false }  
    city:             { type: string(120), notnull: false } 
    description:      { type: clob, extra: markdown }  
    photo:            { type: integer }  
    country:          { type: integer }  
    datepayement:     { type: date, notnull: false }  
    expertise:        { type: integer } 
    sector:           { type: integer }  
    usertype:         { type: integer }  
    isConsultant:     { type: boolean, notnull: true, default: false }  
    isRecruteur:      { type: boolean, notnull: true, default: false }   
    isSupplier:       { type: boolean, notnull: true, default: false }  
  relations:  
    Photo:  
      class:       DmMedia  
      local:       photo  
      onDelete:    RESTRICT
    Sector:
      class:       Sector  
      local:       sector  
      onDelete:    RESTRICT
    Expertise:
      class:       Expertise  
      local:       expertise  
      onDelete:    RESTRICT	  
    Usertype:
      class:       Usertype  
      local:       usertype  
      onDelete:    RESTRICT	
    Country:
      class:       Country  
      local:       country  
      onDelete:    RESTRICT	
Cv:
  columns:
    title:             { type: string(100), notnull: true }
    description:       { type: clob, extra: markdown }
    datedisponibilite: { type: date, notnull: false }  
    user:              { type: integer, notnull: true }  
    tarif:             { type: string(120), notnull: false }
    isvisible:         { type: boolean, notnull: true, default: false }
    isdisponible:      { type: boolean, notnull: true, default: false }
  relations:  
    User:  
      class: DmUser  
      local: user  
      foreignAlias:   Cv
Experience:
  columns:
    title:          { type: string(100), notnull: true }
    description:    { type: clob, extra: markdown }
    datedeb:        { type: date, notnull: false } 
    datefin:        { type: date, notnull: false } 
    cv:             { type: integer } 
  relations:
    Cv:
      class:       Cv  
      local:       cv  
      foreignAlias:   Experience
Hotideas:  
  actAs:  
    DmSortable:  
    I18n:  
      fields:         [ title, extract, body, is_active ]  
      actAs:  
        Timestampable:  
        DmVersionable:  
  columns:  
    title:            { type: string(120), notnull: true }  
    extract:          { type: string(2000), notnull: true }  
    price:            { type: string(80), notnull: true } 
    body:             { type: clob, extra: markdown }  
    image:            { type: integer } 
    categoryidea:     { type: integer } 
    author:           { type: integer, notnull: true }  
    is_active:        { type: boolean, notnull: true, default: false }  
  relations:
    Categoryidea:  
      class:          Categoryidea  
      local:          categoryidea  
      foreignAlias:   Hotideas 
    Image:  
      class:          DmMedia  
      local:          image  
      foreignAlias:   Hotideas  
    Author:  
      class: DmUser  
      local: author  
      foreignAlias:   Hotideas
Subjobcategory:
  columns:
    title:          { type: string(100), notnull: true }
    jobcategory:       { type: integer } 
  relations:
    Jobcategory:
      class:       Jobcategory  
      local:       jobcategory  
      foreignAlias:   Subjobcategory
Job:
  columns:
    title:            { type: string(100), notnull: true }
    description:      { type: clob, extra: markdown }
    city:             { type: string(120), notnull: true }
    dateperemption:   { type: date, notnull: false }
    country:          { type: integer } 
    author:   { type: integer } 
    subjobcategory:   { type: integer } 
  relations:
    Subjobcategory:
      class:       Subjobcategory  
      local:       subjobcategory  
      foreignAlias:   Job
    Country:
      class:       Country  
      local:       country  
      foreignAlias:   Job
    Author:  
      class: DmUser  
      local: author  
      foreignAlias:   Job
Forumcategory:
  columns:
    title:          { type: string(255), notnull: true }
    strippedname:   { type: string(255), notnull: true }
    description:    { type: clob, extra: markdown } 
    rank:           { type: integer } 
    created_at:     { type: date, notnull: false } 
Forum:
 columns:
    title:         { type: string(255), notnull: true }
    description:   { type: clob, extra: markdown } 
    rank:          { type: integer } 
    category:      { type: integer } 
    created_at:    { type: date, notnull: false } 
    updated_at:    { type: date, notnull: false } 
    stripped_name: { type: string(255), notnull: true }
    latest_post:   { type: integer } 
    nb_posts:      { type: integer } 
    nb_topics:     { type: integer } 
Forumtopic:
 columns:
    title:          { type: string(255), notnull: true }
    is_sticked:     { type: boolean, default: false }
    is_locked:      { type: boolean, default: false }
    forum:          { type: integer }
    created_at:     { type: date, notnull: false } 
    updated_at:     { type: date, notnull: false } 
    latest_post:    { type: integer }
    author:         { type: integer }
    stripped_title: { type: string(255), notnull: true }
    nb_posts:       { type: integer, default: 0 }
    nb_views:       { type: integer, default: 0 }
Forumpost:
 columns:
    title:          { type: string(255), notnull: true }
    content:        { type: clob, extra: markdown } 
    topic:          { type: integer }
    author:         { type: integer }
    created_at:     { type: date, notnull: false } 
    forum:          { type: integer }
    author_name:    { type: string(255), notnull: true }
Forumtopicview:
 columns:
    author:       { type: integer }
    topic:        { type: integer }
    created_at:   { type: date, notnull: false } 